tinylibrary/views.py
from database import db, login_manager

from flask import render_template, request, redirect, url_for, flash, jsonify
from flask.blueprints import Blueprint
from flask_wtf import Form
from wtforms.fields.html5 import URLField, DateTimeField, EmailField
from wtforms import StringField, HiddenField, PasswordField, validators
from wtforms.ext.sqlalchemy.fields import QuerySelectField
from flask.ext.login import login_user, logout_user, current_user, login_required

from datetime import datetime

from models import Book, Room, Checkout, Person, Admin
from validators import ValidateIsbn


tinylibrary_app = Blueprint('tinylibrary_app', __name__,
    template_folder='templates', static_folder='static')

#########
# Forms #
#########

class AddBookForm(Form):
    isbn13 = StringField(label='ISBN', validators=[validators.DataRequired(), ValidateIsbn()])
    inside_cover_id = StringField(label='Custom ID')
    title = StringField()
    description = StringField()
    thumbnail_url = URLField(validators=[validators.url])

class CheckoutForm(Form):
    checkout_date = DateTimeField(format='%Y/%m/%d %H:%M',validators=[validators.DataRequired()], default=datetime.today())
    room = QuerySelectField(query_factory=lambda:db.session.query(Room), allow_blank=False)
    person = QuerySelectField(query_factory=lambda:db.session.query(Person).filter(Person.active), allow_blank=False)
    # book is assigned in the view

class ReturnForm(Form):
    return_date = DateTimeField(format='%Y/%m/%d %H:%M',validators=[validators.DataRequired()], default=datetime.today())

class LoginForm(Form):
    username = EmailField('Username (Email address)', [validators.DataRequired(), validators.Email()])
    password = PasswordField(validators=[validators.DataRequired()])

# XXX: never used
# class BookFilterForm(Form):
#     is_available = SelectField("Checked out",
#         choices=[('',''),("True","Available"),("False","Checked out")])
#     title_contains = StringField()

#########
# Views #
#########

# Authenticated views

@tinylibrary_app.route('/add_books/', methods=['GET','POST'])
@login_required
def add_books():
    add_book_form = AddBookForm()
    if add_book_form.validate_on_submit():
        print 'got add book form %s' % add_book_form

        new_book = Book(isbn13=add_book_form.isbn13.data, inside_cover_id=add_book_form.inside_cover_id.data, title=add_book_form.title.data, description=add_book_form.description.data, thumbnail_url=add_book_form.thumbnail_url.data)

        db.session.add(new_book)
        db.session.commit()

        flash('Added ISBN#%s "%s"' % (add_book_form.isbn13.data, add_book_form.title.data), category='success')
        return redirect(url_for('.add_books'))
    if add_book_form.is_submitted():
        flash('There was an error with your submission', category='danger')
    return render_template('add_books.html', form=add_book_form)

@tinylibrary_app.route('/checkout/<int:book_id>', methods=['GET','POST'])
@login_required
def checkout(book_id):
    selected_book = Book.query.get_or_404(book_id)
    if not selected_book.is_available:
        flash('"%s" (ID: %s) is already checked out. It must be returned before you can check it out.' % (selected_book.title, selected_book.inside_cover_id), category='danger')
        return redirect(url_for('.books'))

    checkout_form = CheckoutForm()
    if checkout_form.validate_on_submit():
        new_checkout = Checkout(checkout_date=checkout_form.checkout_date.data, book=selected_book, person=checkout_form.person.data, room=checkout_form.room.data)

        db.session.add(new_checkout)
        db.session.commit()

        flash('Checked out %s to Room %s' % (selected_book.title, checkout_form.room.data.id), category='success')
        return redirect(url_for('.books'))
    # return render_template('checkout.html', book=bk, people=people, rooms=rooms)
    return render_template('checkout.html', book=selected_book, form=checkout_form)

@tinylibrary_app.route('/return/<int:book_id>', methods=['GET','POST'])
@login_required
def return_book(book_id):
    selected_book = Book.query.get_or_404(book_id)
    if selected_book.is_available:
        flash('"%s" (ID: %s) is not checked out. It cannot be returned.' % (selected_book.title, selected_book.inside_cover_id), category='danger')
        return redirect(url_for('.books'))
    return_form = ReturnForm()
    if return_form.validate_on_submit():
        open_checkout = selected_book.open_checkout()
        open_checkout.return_date = return_form.return_date.data
        db.session.add(open_checkout)
        db.session.commit()
        flash('Returned %s (ID: %s)' % (selected_book.title, selected_book.inside_cover_id), category='success')
        return redirect(url_for('.books'))
    return render_template('return_book.html', book=selected_book, form=return_form)

@tinylibrary_app.route('/add_students/', methods=['GET','POST'])
@login_required
def students_bulk_add():
    if request.method == 'POST':
        # should get JSON data from AJAX request
        data = request.get_json()
        print 'got bulk student data:', data
        # TODO: persist the data
        print 'TODO: add student data to database'
        flash('Added students', category='success')
        # return the URL for json redirect
        return jsonify({'redirect':url_for('.books')})
    return render_template('add_students_csv.html')

# Public views

@tinylibrary_app.route('/')
def redirect_to_books():
    return redirect(url_for('tinylibrary_app.books'))

@tinylibrary_app.route('/books/')
def books():
    # id overrides all other args
    if 'id' in request.args:
        bk = Book.query.get_or_404(request.args.get('id'))
        return render_template('single_book.html', book=bk)
    elif request.args:
        # If there are args that don't include id, filter by all of them
        # TODO: make this more useful/robust, use fuzzy matching on title & description

        # Base book query
        book_query = Book.query

        if 'title_contains' in request.args:
            title_sub = request.args['title_contains'].strip()
            # don't waste the extra filter on blank string
            if title_sub != "":
                book_query = book_query.filter( Book.title.like('%' + title_sub + '%') )
        if 'is_available' in request.args:
            is_unavailable_query = Book.checkout.any(return_date=None)
            if request.args['is_available'] == 'True':
                # available books
                book_query = book_query.filter(~is_unavailable_query)
                # not available (checked out) books
            else:
                book_query = book_query.filter(is_unavailable_query)

        # selected_books = Book.query.filter_by(**request.args.to_dict()).all()

        return render_template('show_books.html', books=book_query.all())

    # No args
    return render_template('show_books.html', books=Book.query.all())

@tinylibrary_app.route('/login', methods=['GET','POST'])
def login():
    login_form = LoginForm()
    if login_form.validate_on_submit():
        registered_user = Admin.query.filter_by(username=login_form.username.data).first()
        if registered_user and registered_user.is_correct_password(login_form.password.data):
            login_user(registered_user, remember=True)
            flash('Logged in successfully. Hello %s!' % (registered_user.username), category='success')
            return redirect(url_for('tinylibrary_app.books'))
        flash('Username or Password is invalid' , category='warning')
    return render_template('login.html', form=login_form)

@tinylibrary_app.route('/logout')
def logout():
    if current_user.is_authenticated:
        flash('Logged out %s.' % current_user.username, category='success')
        logout_user()
    else:
        flash('Already logged out.', category='danger')
    return redirect(url_for('tinylibrary_app.books'))

@login_manager.user_loader
def load_user(admin_id):
    return Admin.query.get(admin_id)

tinylibrary/templates/add_books.html
{% extends 'base.html' %}
{% from 'flash_macros.html' import simple_flash %}
{% from 'bootstrap_form_macros.html' import render_form %}
{% block title %}Add books to database{% endblock %}
{% block body %}
{{ simple_flash() }}
<!-- <form method="POST" action={{ url_for('.add_books') }}>
    <div class="form-group">
        \{\{ form_uls(form) }}
        <input type="submit" value="+">
    </div>
</form> -->
<div class="add-book-form">
    {{ render_form(form, action_url=url_for('.add_books'), action_text="+") }}
</div>
<img id="cover_img" src="{{ url_for('.static', filename='img/iranian_cover.jpg') }}" alt='book cover image'>
{% endblock %}
{% block scripts %}
{{ super() }}
<script src="{{ url_for('.static', filename='js/isbnjs-1.0.0/isbn.js') }}"></script>
<script src="{{ url_for('.static', filename='js/add_books.js') }}"></script>
{% endblock %}

tinylibrary/templates/add_students_csv.html
{% extends 'base.html' %}
{% from 'flash_macros.html' import simple_flash %}
{% block title %}Bulk-add students to database{% endblock %}
{% block body %}
{{ simple_flash() }}
<textarea id='csv_text' style='height:200px;' default='Paste comma-separated data here'></textarea>
<button id="parse_button">Enter</button>
{% endblock %}
{% block scripts %}
{{ super() }}
<script src="{{ url_for('.static', filename='js/jquery.csv.min.js') }}"></script>
<script>
    function parse_csv(callback) {
        var input = $('#csv_text').val();
        // XXX: hack for tab-delimited input
        input = input.replace(/\t/g,',');
        try {
            var data = $.csv.toObjects(input);
        } catch(e) {
            alert('Error: text is not valid CSV. (' + e + ')');
            return e;
        }
        callback(data);
    }

    function post_data(data) {
        json_data = JSON.stringify(data);
        $.ajax({
            url:'{{ url_for('.students_bulk_add')}}',
            type:'POST',
            data:json_data,
            contentType: "application/json; charset=utf-8",
            dataType:"json",
            success: function(response){
            if (response.redirect !== undefined && response.redirect) {
                window.location.href = response.redirect;
            } else {
                console.warn('Invalid response from server: ', response);
            }
        }});
    }

    $('#parse_button').click(function(){parse_csv(post_data);})
</script>
{% endblock %}

tinylibrary/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <link rel="shortcut icon" href="{{ url_for('.static', filename='favicon.ico') }}">
        <link rel="stylesheet" type="text/css" href="{{ url_for('.static', filename='css/base.css') }}">
        <!-- Bootstrap: Latest compiled and minified CSS -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
        <!-- Optional theme -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
        {% block style %}
        {% endblock %}
        <title>{% block title %}{% endblock %}</title>
    </head>
    <body>
        {% block menu %}
            <nav id="nav_menu" class="navbar navbar-default">
                <div class="container-fluid">
                <div class="navbar-header"><ul class="nav navbar-nav">
                    <li><a href="{{ url_for("tinylibrary_app.books")}}">Books Home</a></li>
            {% if current_user.is_authenticated %}
                    <li><a href="{{ url_for("tinylibrary_app.add_books")}}">Add Books</a></li>
                    <li><a href="{{ url_for("tinylibrary_app.students_bulk_add")}}">Add Students</a></li>
                    <li><a href="{{ url_for("tinylibrary_app.logout")}}">Log Out</a></li>
            {% else %}
                    <li><a href="{{ url_for("tinylibrary_app.login")}}">Admin Login</a></li>
            {% endif %}
            </ul></div>
            </div>
        </nav>
        {% endblock %}

        {% block body %}
        {% endblock %}

        {% block scripts %}
            <!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script> -->
            <script src="{{ url_for('.static', filename='js/jquery-1.12.1.min.js') }}"></script>
            <!-- Bootstrap: Latest compiled and minified JavaScript -->
            <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
        {% endblock %}
    </body>
</html>

tinylibrary/templates/bootstrap_form_macros.html
{# Renders field for bootstrap 3 standards.

    Params:
        field - WTForm field
        kwargs - pass any arguments you want in order to put them into the html attributes.
        There are few exceptions: for - for_, class - class_, class__ - class_

    Example usage:
        {{ macros.render_field(form.email, placeholder='Input email', type='email') }}
#}
{% macro render_field(field, label_visible=true) -%}

    <div class="form-group {% if field.errors %}has-error{% endif %} {{ kwargs.pop('class_', '') }}">
        {% if (field.type != 'HiddenField' and field.type !='CSRFTokenField') and label_visible %}
            <label for="{{ field.id }}" class="control-label">{{ field.label }}</label>
        {% endif %}
        {{ field(class_='form-control', **kwargs) }}
        {% if field.errors %}
            {% for e in field.errors %}
                <p class="help-block">{{ e }}</p>
            {% endfor %}
        {% endif %}
    </div>
{%- endmacro %}

{# Renders checkbox fields since they are represented differently in bootstrap
    Params:
        field - WTForm field (there are no check, but you should put here only BooleanField.
        kwargs - pass any arguments you want in order to put them into the html attributes.
        There are few exceptions: for - for_, class - class_, class__ - class_

    Example usage:
        {{ macros.render_checkbox_field(form.remember_me) }}
 #}
{% macro render_checkbox_field(field) -%}
    <div class="checkbox">
        <label>
            {{ field(type='checkbox', **kwargs) }} {{ field.label }}
        </label>
    </div>
{%- endmacro %}

{# Renders radio field
    Params:
        field - WTForm field (there are no check, but you should put here only BooleanField.
        kwargs - pass any arguments you want in order to put them into the html attributes.
        There are few exceptions: for - for_, class - class_, class__ - class_

    Example usage:
        {{ macros.render_radio_field(form.answers) }}
 #}
{% macro render_radio_field(field) -%}
    {% for value, label, _ in field.iter_choices() %}
        <div class="radio">
            <label>
                <input type="radio" name="{{ field.id }}" id="{{ field.id }}" value="{{ value }}">{{ label }}
            </label>
        </div>
    {% endfor %}
{%- endmacro %}

{# Renders WTForm in bootstrap way. There are two ways to call function:
     - as macros: it will render all field forms using cycle to iterate over them
     - as call: it will insert form fields as you specify:
     e.g. {% call macros.render_form(form, action_url=url_for('login_view'), action_text='Login',
                                        class_='login-form') %}
                {{ macros.render_field(form.email, placeholder='Input email', type='email') }}
                {{ macros.render_field(form.password, placeholder='Input password', type='password') }}
                {{ macros.render_checkbox_field(form.remember_me, type='checkbox') }}
            {% endcall %}

     Params:
        form - WTForm class
        action_url - url where to submit this form
        action_text - text of submit button
        class_ - sets a class for form
    #}
{% macro render_form(form, action_url='', action_text='Submit', class_='', btn_class='btn btn-default') -%}

    <form method="POST" action="{{ action_url }}" role="form" class="{{ class_ }}">
        {{ form.hidden_tag() if form.hidden_tag }}
        {% if caller %}
            {{ caller() }}
        {% else %}
            {% for f in form %}
                {% if f.type == 'BooleanField' %}
                    {{ render_checkbox_field(f) }}
                {% elif f.type == 'RadioField' %}
                    {{ render_radio_field(f) }}
                {% else %}
                    {{ render_field(f) }}
                {% endif %}
            {% endfor %}
        {% endif %}
        <button type="submit" class="{{ btn_class }}">{{ action_text }} </button>
    </form>
{%- endmacro %}

tinylibrary/templates/checkout.html
{% extends 'base.html' %}

{% block style %}
<link rel="stylesheet" type="text/css" href="{{ url_for('.static', filename='css/jquery.datetimepicker.css') }}">
{% endblock %}

{% block title %}Checkout {{ book.title }}{% endblock %}
{% block body %}
<h1>Checkout <em>{{ book.title }}</em></h1>
<div id=book>
    <h2>Book info</h2>
    <div id='title'>Title: {{ book.title }}</div>
    <div id='isbn13'>ISBN13: {{ book.isbn13 }}</div>
    <div id='inside_cover_id'>Custom ID: {{ book.inside_cover_id }}</div>
    <img id="thumbnail_img" src="{{book.thumbnail_url}}">
</div>

<!-- TODO: make DRY with macro -->
<form method="POST" action={{ url_for('.checkout', book_id=book.id) }}>
    <ul>{{ form.hidden_tag() }}
    {% for field in form %}
        {% if field.widget.input_type != 'hidden' %}
            <li>{{ field.label }}
        {% endif %}
        {{ field }}
        {% if field.errors %}
            <ul class="errors">{% for error in field.errors %}<li>{{ error }}</li>{% endfor %}</ul>
        </li>{% endif %}
    {% endfor %}</ul>
    <input type="submit" value="+">
</form>

{% endblock %}

{% block scripts %}
{{ super() }}
<script src="{{ url_for('.static', filename='js/jquerydatetimepicker/jquery.datetimepicker.full.min.js') }}"></script>
<script>
$('input#checkout_date').datetimepicker();
</script>
{% endblock %}

tinylibrary/templates/flash_macros.html
{% macro simple_flash() %}
    {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
          {% for category, message in messages %}
            <div class="alert alert-{{category}} alert-dismissible">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                {{ message }}
            </div>
          {% endfor %}
        {% endif %}
    {% endwith %}
{% endmacro %}

tinylibrary/templates/form_macros.html
{% macro form_uls(form) %}
<ul>{{ form.hidden_tag() }}
{% for field in form %}
    {% if field.widget.input_type != 'hidden' %}
        <li>{{ field.label }}
    {% endif %}
    {{ field }}
    {% if field.errors %}
        <ul class="errors">{% for error in field.errors %}<li>{{ error }}</li>{% endfor %}</ul>
    </li>{% endif %}
{% endfor %}</ul>
{% endmacro %}

tinylibrary/templates/login.html
{% extends 'base.html' %}
{% from 'flash_macros.html' import simple_flash %}
{% from 'form_macros.html' import form_uls %}
{% block title %}Admin Login{% endblock %}
{% block body %}
{{ simple_flash() }}
<h1>Admin Login</h1>
<form method="POST" action={{ url_for('.login') }}>
    {{ form_uls(form) }}
    <input type="submit" value="Login">
</form>
{% endblock %}

tinylibrary/templates/return_book.html
{% extends 'base.html' %}
{% from 'form_macros.html' import form_uls %}

{% block style %}
<link rel="stylesheet" type="text/css" href="{{ url_for('.static', filename='css/jquery.datetimepicker.css') }}">
{% endblock %}

{% block title %}Return {{ book.title }}{% endblock %}
{% block body %}
<h1>Return '{{ book.title }}'</h1>
<div>{% if book.thumbnail_url %}<img src="{{ book.thumbnail_url }}">{% endif %}</div>
<div>Last checked out {% with %}{% set checkout = book.open_checkout() %} by {{ checkout.person }} to Room {{ checkout.room }} on {{checkout.checkout_date }}{% endwith %}</div>
<form method="POST" action={{ url_for('.return_book', book_id=book.id) }}>
    {{ form_uls(form) }}
    <input type="submit" value="Return">
</form>

{% endblock %}

{% block scripts %}
{{ super() }}
<script src="{{ url_for('.static', filename='js/jquerydatetimepicker/jquery.datetimepicker.full.min.js') }}"></script>
<script>
$('input#return_date').datetimepicker();
</script>
{% endblock %}

tinylibrary/templates/show_books.html
{% extends 'base.html' %}
{% from 'flash_macros.html' import simple_flash %}

{% block title %}All the books{% endblock %}
{% block body %}
{{ simple_flash() }}
<nav id="book_filter" class="navbar navbar-default"><div class="container-fluid">
    <form class="navbar-form navbar-left" method="GET" action={{ url_for('.books') }}><div class="form-group">
        <label>
            Availability:
            <select name="is_available" class="form-control">
                <option disabled selected value>---</option>
                <option value="True">Available</option>
                <option value="False">Checked out</option>
            </select>
        </label>
        <label>
            Title contains: <input name="title_contains" type="text" class="form-control"/>
        </label>
        <button type="submit">Go</button>
    </div></form>
</div></nav>
<table class="table">
    <tr>
        <th>Cover Image</th>
        <th>Title</th>
        <th>Inside cover ID</th>
        <th>Description</th>
        <th>ISBN</th>
        <th>Date added</th>
    </tr>
    {% for book in books %}
    <tr>
        <td>{% if book.thumbnail_url %}<img src="{{ book.thumbnail_url }}">{% endif %}</td>
        <td><a href="{{ url_for('.books', id=book.id)}}">{{ book.title }}</a>
            {% if not book.is_available %}
                <p class="checked-out">CHECKED OUT</p>
            {% endif %}
        </td>
        <td>{{ book.inside_cover_id }}</td>
        <td>{% if book.description%}{{ book.teaser() }}...{% endif %}</td>
        <td>{{ book.isbn13 }}</td>
        <td>{{ book.date_added }}</td>
    </tr>
    {% endfor %}
</table>
{% endblock %}

tinylibrary/templates/single_book.html
{% extends 'base.html' %}
{% block title %}{{ book.title }}{% endblock %}
{% block body %}
<table class="table table-striped">
    <tr>
        <th>Title:</th>
        <td>{{ book.title }}</td>
    </tr>
    <tr>
        <th>Status:</th>
        <td>
            {% if not book.is_available %}
            <a href="{{ url_for('.return_book', book_id=book.id)}}" class="btn btn-primary">RETURN</a>
            Checked out {{ book.last_checked_out() }}.
            {% else %}
                <a href="{{ url_for('.checkout', book_id=book.id)}}" class="btn btn-primary">AVAILABLE</a>
            {% endif %}
        </td>
    </tr>
    <tr>
        <th>ISBN13:</th> <td> {{ book.isbn13 }}</td>
    </tr>
    <tr>
        <th>Custom ID:</th>
        <td>{{ book.inside_cover_id }}</td>
    </tr>
    <tr>
        <th>Description:</th>
        <td>{{ book.description }}</td>
    </tr>
    <tr>
        <th>Cover Image:</th>
        <td><img id="thumbnail_img" src="{{book.thumbnail_url}}"></td>
    </tr>
</table>
{% endblock %}